version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-fms-data:/var/lib/postgresql/data
    env_file: ./postgres.env
    # environment:
    #   - POSTGRES_PASSWORD=postgres
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_DB=public
    networks:
      - fms

volumes:
  postgres-fms-data:
    driver: local
    
networks:
  fms:
    driver: bridge